name: CI_DEPLOY

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install dependencies
        run: npm install

      - name: Deploy
        run: |
          git config --global user.name "samkoi"
          git config --global user.email "samitkoirala@hotmail.com"
          git remote set-url origin https://${personal_access_token}@github.com/samkoi/deployment
          npm run deploy
        env:
          personal_access_token: ${{ secrets.ACCESS_TOKEN_DEPLOY }}
